spring:
  datasource:
    platform:
      url: jdbc:h2:mem:mydb
      username: sa
      password: sa
      driverClassName: org.h2.Driver
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8081


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.generate_statistics: false
      hibernate.format_sql: true
      hibernate.show_sql: true
      hibernate.cache.use_second_level_cache: false
      hibernate.dialact: org.hibernate.dialect.H2Dialect
    database: H2
